### ISSUE TITLE
iOS runtime error

### ISSUE THREAD

**Issue by alebianco** [alebianco/ANE-Google-Analytics#1]
On iOS it throws an error:

Unable to find named traits: eu.alebianco.core::Enum

**Comment by edzis** [comment]
Is this one fixed? I see that there are commits newer that this issue.

**Comment by alebianco** [comment]
It should be fixed, but I could only test it only on the iOS simulator.

I was waiting for @digitaljohn for some feedback, since he's the one who have reported it, but i got none. That's the main reason the issue it's still open.

If you care to test it and report back it will be much appreciated :)

**Comment by digitaljohn** [comment]
My apologies for the delay. We have not had a chance to retest as are working on other parts of this mammoth cross-platform starling project.

Hopefully we will be able to take another look early next week.

**Comment by digitaljohn** [comment]
This appears to be fixed... but I am getting the same error on Android. Ill open another Issue...
