### ISSUE TITLE
Causes Android app to force-quit

### ISSUE THREAD

**Issue by sarahnorthway** [alebianco/ANE-Google-Analytics#10]
I've got this working beautifully in iOS (iPhone 4s w/ 5.0.1), but on Android (Nexus One w/ 2.3.6) it consistently causes the app to crash after 5-10 seconds. I don't see anything useful in the logcat but I'd be happy to help debug this. I'm building with AIR 3.5.

**Comment by alebianco** [comment]
i've a device with 2.3.7 running, will check again tomorrow but last time i built the project everything was working fine.
could you give me some more details on when the crash seems to happen? upon initialization? after some specific method call?

**Comment by sarahnorthway** [comment]
The exact timing varies, but it crashes after several seconds of sitting there - no input or calls from my code. Always after logging is enabled and the first pageview sent. I thought it was just coincidence at first since this phone's cranky at the best of times, but after enabling/disabling the logging half a dozen times I'm sure. Seems like it must be some kind of background process or something delayed?

**Comment by alebianco** [comment]
i just pushed a new release with the latest SDK from Google
i tested it on my android 2.3.7 (it's an HTC Desire with a custom rom) and it works ok, no crashes on my end

if still have problems with this release: 
try using a manual dispatch by setting Analytics.getInstance().dispatchManually = true; and then calling Analytics.getInstance().dispatch(); when you're ready to send your hits

and let me know what happens. in case of errors, if you could also provide a system log it would be helpful probably

**Comment by xastor** [comment]
I had this problem too, but with another ane.  I was able to fix it by going back to air 3.5 (I was using 3.6 beta).

**Comment by SlavomirDurej** [comment]
is there any news on this ? I'm using AIR 3.7 and I'm having exactly the same problem as Sarah.. Going back to v3.5 doesn't really seems like a good solution..

**Comment by SlavomirDurej** [comment]
one thing I just noticed, I've added a couple of android permissions to the app and it stopped crashing (might be coincidence, but hopefully not) Added access Network State, Access Wifi State, Access Fine Location, Read phone state, write external storage and internet permissions.. 

Are all of those needed ? Which ones does this extension actually need ?

**Comment by alebianco** [comment]
Still have to investigate it properly, but never encountered the problem myself. I don't know of any special requirement of permissions, beside internet access. 
I have a demo project in my repos which Is working and you can use to compare. Also, i just published an update that may fix some issues. 
If that doesn't help, could you upload somewhere a small project that has the problem? It would help me a lot..
