### ISSUE TITLE
iOS ipa compile error

### ISSUE THREAD

**Issue by arnovanoordt** [alebianco/ANE-Google-Analytics#13]
Hi Alebianco,

Great work on the new version! However I'm running into a little problem when I try to compile my ipa (using the commandline).
This is the error:
"Installation Error: PackageInspectionFailed."

..and here is the appropriate part of the logging:
installd[3647] <Error>: 0x2ff56000 handle_install: Install of "/var/mobile/Media/PublicStaging/Cubles-dev.ipa" requested by mobile_installation_proxy
installd[3647] <Error>: 0x2ff56000 peruse_package: App info dict loaded from "/var/tmp/install_staging.Y0G6U5/foo_extracted/Payload/CublesLite.app" did not have bundle identifier
installd[3647] <Error>: 0x2ff56000 stage_package: Could not peruse package at /var/tmp/install_staging.Y0G6U5/foo_extracted
mobile_installation_proxy[3662] <Error>: 0x3bb0bb88 MobileInstallationInstall: failed with -1
mobile_installation_proxy[3662] <Error>: handle_install: Installation failed
installd[3647] <Error>: 0x2ff56000 MobileInstallationInstall_Server: Could not stage the package
installd[3647] <Error>: 0x2ff56000 cleanup_pack_state: Could not nuke /var/tmp/install_staging.Y0G6U5
installd[3647] <Error>: 0x2ff56000 handle_install: API failed

I can compile the swf without any problems but when I add "<extensionID>eu.alebianco.air.extensions.analytics.NativeGATracker</extensionID>" to the descriptor xml this error keeps appearing.

I'm compiling with AIR 3.7 but I also tried other versions, all with the same result.

Hope this makes any sens to you and hope you can fix this.

Thanks, Arno

**Comment by alebianco** [comment]
it may be just some configuration of the project or the commandline you're running.
could you paste somewhere (like on pastebin or a gist) the app descriptor xml you're using and the complete command line for compiling?

**Comment by arnovanoordt** [comment]
Thanks for the quick reply!
Here is the descriptor: http://pastebin.com/8MDsnL9P
And here is the commandline stuff: http://pastebin.com/DP13xMzL

PS I run my stuff on a remote mac so ther is som copying of files to that laptop but that should have no influence on the executition of the rest of the script

**Comment by alebianco** [comment]
i'm doing some research on the problem and it's tricky, still not sure what's the cause.
you said you get the error while compiling? because most of the references i found online says it shows up when deploying on the device.
also, does it happen only on an actual device? or on the emulator too?

**Comment by arnovanoordt** [comment]
My bad, it's indeed during deploy; direct throught adt and through itunes as well (with itunes the loader bar just stops around 90% and then the installation just hangs). I don't have an emulator so I'm not sure if the problem arises there too. I see if I can get an it to work on an emulator later on today.

**Comment by arnovanoordt** [comment]
Here are the errors I get when I try to run it om the emulator:

*Compile:
ld: warning: could not create compact unwind for __Unwind_Resume: non-standard r                                                                  egister 0 being saved in prolog
ld: warning: could not create compact unwind for __Unwind_ForcedUnwind: non-stan                                                                  dard register 0 being saved in prolog
ld: warning: could not create compact unwind for __Unwind_RaiseException: non-st                                                                  andard register 0 being saved in prolog
ld: warning: could not create compact unwind for __Unwind_Resume_or_Rethrow: non                                                                  -standard register 0 being saved in prolog

*Compile done..

*Install on simulator:

Installation failed with error: Error Domain=NSCocoaErrorDomain Code=513 "âeu.al                                                                  ebianco.air.extensions.analytics.api.xmlâdocsâ
                                                  Copy
), NSDestinationFilePath=/Users/arnovanoordt/Library/Application Support/iPhone                                                                   Simulator/6.1/Applications/882E8F32-787A-4750-95B9-DBAC1CF5E249/CublesLite.app/M                                                                  ETA-INF/AIR/extensions/eu.alebianco.air.extensions.analytics.NativeGATracker/doc                                                                  s/eu.alebianco.air.extensions.analytics.api.xml, NSFilePath=/var/folders/x_/6q3q                                                                  5p1d2qz48r5cvzjkvxyc0000gn/T/f9ccc2c6-584f-4233-8551-e8f7c0b99901/Payload/Cubles                                                                  Lite.app/META-INF/AIR/extensions/eu.alebianco.air.extensions.analytics.NativeGAT                                                                  racker/docs/eu.alebianco.air.extensions.analytics.api.xml, NSUnderlyingError=0x1                                                                  0011a500 "The operation couldnât be completed. Permission denied"}

Compiling without <extensionID>eu.alebianco.air.extensions.analytics.NativeGATracker</extensionID> gives no errors and the app will run just fine (but the tracking won't work of course).
Hope this info is of any use to you.

**Comment by alebianco** [comment]
hum, weird, i got no errors on the emulator
i'm going to try and compile a version without the documentation embedded (since the problems seems to come from the doc folder) later today and upload it somewhere for you to try

**Comment by alebianco** [comment]
could you try with the latest release in the dev branch? can't test on a real device yet, but on the emulator seems to be working ...

**Comment by arnovanoordt** [comment]
Works like a charm! Thanks for the support!

**Comment by par128** [comment]
Hey, Alessandro!
When I'm trying to debug our app with Flash Builder,
the same problem occurs now (the latest NativeGATracker-v2.0.4.ane)
I get aforementioned error "PackageInspectionFailed".
When I remove NativeGATracker from the app, the debug build is successful and the app is deployed to the device.

Adobe AIR 4.0, building for iOS only

Can you help, please?

Thanks for the extension, we are using it in in our YoWindow weather project - http://yowindow.com

**Comment by alebianco** [comment]
i haven't changed the build number for the past couple builds (i know! it was a mistake!) so, is it a recent build or an old one? can you try with the latest?
I haven't seen that problem since i removed the docs and surely i haven't added them back.

if that doesn't work drop me an email with the log of the error and the app descriptor please
