### ISSUE TITLE
Tracked data not showing in Google Analytics

### ISSUE THREAD

**Issue by protozoo** [alebianco/ANE-Google-Analytics#15]
Hi there!

I'm trying to use this extension in my iOS app but don't seem to be able to get the tracker data in GA. I'm using this code:

if (GATracker.isSupported()) {
                trace( "Google Analytics is supportd" );
                _tracker = GATracker.getInstance();
                _tracker.startNewSession("XXXXXX", 20);
                _tracker.trackPageView("/init");
            }else{
                trace( "Google Analytics is NOT supportd" );
            }
GATracker.isSupported() returns true, and I get no errors in the FB console.
Later in the application flow, I also perform some more "trackPageView" and "trackEvent" calls.
I checked the xCode's organizer console log as suggested in other issues in this repo, but not sure what to look for. 

I'm using the compiled ANE downloaded from the repo's main page (I guess that's the master branch), and the GA profile is a newly created one as "app".

Any ideas what could be wrong?

Thanks a lot for your work and help!

**Comment by alebianco** [comment]
the "old" (as in "the one in the master branch") doesn't work with the "app" profile, due to google's restrictions; if you want to use that version you must use the "web" profile.
otherwise (and i encourage this option) you can use the version in the development branch, which will work just fine.
The API is quire different from the first version and it's still undergoing some small changes and testing, but it should be stable enough to be used in production.

**Comment by protozoo** [comment]
Hi Alessandro,

thanks for the reply. In don't see the compiled ANE in the development version. Am i supposed to compile it myself? (not sure how to do it since I haven't worked with Objctive-C / xCode further that some very basic tutorials a longo time ago).

Thanks again!

**Comment by alebianco** [comment]
there shoud be a release folder with a zip inside, you'll find the compile
version and the documentation inside

Alessandro

**Comment by protozoo** [comment]
Hi Alessandro,

sorry if this is a bit lame, but can't find the release folder. The ANE I've been using until now is the one I found in the master branch under the "bin" folder. 
Afterwards, I've pulled the development branch but I only see a "build" and "source" folders there. Am I missing something?

Thanks again

**Comment by alebianco** [comment]
sorry, my fault, I probably removed it in one of the latest commits.
I'm going to rebuild it a push the release folder. Give it 10-15 mins and
check again the development branch

Alessandro

**Comment by protozoo** [comment]
Hi again,

thanks, I downloaded it, upgraded my AIR SDK to 3.7 (latest from Adobe), and could compile my app and deploy to device without problem. I also replaced the ANE-related functions since looks like the development version is different that the master one. I.e:

I changed this:

if (GATracker.isSupported()) {
    var tracker:GATracker = GATracker.getInstance();
    tracker.startNewSession("UA-00000000-0", interval);
    tracker.trackPageView("/custom/view/url");
}

to this:

if (Analytics.isSupported()) {
                trace( "Google Analytics is supportd" );
                var analytics:Analytics = Analytics.getInstance();
                _tracker = analytics.getTracker("XXXXXXX");
                _tracker.buildView("/init").track();
            }else{
                trace( "Google Analytics is NOT supportd" );
            }

I'm not seeing anything yet in the GA dashboard, but I guess it will take a while to get updated. Will check again later to see if my events and page views finally got tracked.

Thanks again!

**Comment by protozoo** [comment]
Hi again,

pages and events are now being tracked and displayed in GA, so all is fine.

Thanks a lot for your help!
