### ISSUE TITLE
Updates Required for AIR 3.8

### ISSUE THREAD

**Issue by treefortress** [alebianco/ANE-Google-Analytics#17]
Hi, as per this thread:
http://forums.adobe.com/message/5478318#5478318

Some changes are required to run with AIR 3.8, specifically: 

You will need to change the line:
<option>-ios_version_min 4.0</option>
to:
<option>-ios_version_min 4.2</option>

and rebuild the ANE

**Comment by alebianco** [comment]
will need to check if that has some sort of impact on older versions of AIR
in any case, will do as soon as AIR 3.8 is out of the beta

**Comment by treefortress** [comment]
Cool, thanks! Any chance you can kick out an intermediary build...? 3.8 isn't scheduled to hit for about 2 full months :(

**Comment by alebianco** [comment]
yes i could create a new branch for that but i won't be able to do it until after the weekend
if you can't wait, you can try to build it yourself (and be my guinea pig to see if the build process is easy enough to be used by other people)

**Comment by treefortress** [comment]
Awesome that would be great. I'd totally do that, but I don't have a readily available OSX machine.

**Comment by alebianco** [comment]
are you deploying on ios or android?
if you don't have to deploy to ios, you can build on windows, the build script should be smart enough to compile only the android part of the native code, and test your app on a device (android emulator is not supported by the extension)

**Comment by treefortress** [comment]
The bug only manifests on iOS (I believe) as it's related to the min required iOS SDK. So for Android it already works fine.

**Comment by alebianco** [comment]
the new release should support air 3.8 without issues
