### ISSUE TITLE
How to use with flash pro CC?

### ISSUE THREAD

**Issue by djnr** [alebianco/ANE-Google-Analytics#18]
is there a method/instructions to use this with flash pro?

**Comment by alebianco** [comment]
don't know, never tried
i suppose it will be the same as flash pro cs6
http://www.adobe.com/devnet/air/articles/using-ane-in-flash.html

**Comment by djnr** [comment]
Thank you!

Jenaro Diaz
djnr@djnr.net

**Comment by stugorf** [comment]
djnr,

Did you ever get great ANE to work in Flash Pro. I am trying to implement in Flash Pro Cc and followed the instructions from the Adobe devnet and it links fine. I then imported using 
import eu.alebianco.air.extensions.analytics.Analytics;
import eu.alebianco.air.extensions.analytics.api.ITracker;

However, when compiling i get  error: 1172: Definition eu.alebianco.air.extensions.analytics:Analytics could not be found.

Any thoughts?

**Comment by djnr** [comment]
Copy the folder NativeGATracker-v2.0.4_201401140301 to your project folder, and add the ANE path on the AS3 settings, that makes it available.

**Comment by stugorf** [comment]
djnr, thanks for the quick reply. I added the folder to source path in CC and then tried as a folder in Library path and still my imports cannot find the classes. The folder is in the root of my project but I am not using FB or FD to build my project, just Flash Pro CC. Thank you for any further thoughts...

**Comment by djnr** [comment]
Did you added in the library path as an ANE? by clicking the ANE button?
