### ISSUE TITLE
No GA datas with 1.23 and PackageInspectionFailed with 2.0.4

### ISSUE THREAD

**Issue by nicocolascrete** [alebianco/ANE-Google-Analytics#19]
Hello,

I'm trying to use this extension in my iOS app but don't seem to be able to get the tracker data in GA with "app" profile.. I use the 1.23 version.

I'm trying with 2.0.4 version but I can't install the application... I compile ( air 3.7 & iOS 6.1 ) in app-debug and if I try to install I have this error.
04 - ios-install-ipa:
     [exec] Installation Error: PackageInspectionFailed.

Any ideas what could be wrong?

Thanks a lot for your work and help!

**Comment by pierrickyamago** [comment]
Hello,

same issue with air 3.6 on iOS.

Best Regards

**Comment by alebianco** [comment]
could you try the latest version in the master branch and let me know if it works?
also, does it fail both on the simulator and the device or just the device?

**Comment by pierrickyamago** [comment]
Yes it works well with the latest version in the master branch!

Thank you!

Best Regards

**Comment by alebianco** [comment]
glad to hear :)
