### ISSUE TITLE
Compiling with Air SDK 3.8 fails

### ISSUE THREAD

**Issue by SlavomirDurej** [alebianco/ANE-Google-Analytics#20]
First of all, thanks for all your hard work on this extension it's really useful! 

It works well, when I use AIR SDK 3.7, however when I try to use Air 3.8 (which I have to for other reasons unfortunately, due to a certain bug in 3.7..) I get this error message : 
Packaging failed!
Packaging error message: 
Compilation failed while executing : ld64
Packaging output: 
ld: -pie can only be used when targeting iOS 4.2 or later

I imagine this is due to a minimum iOS sdk compatibility , and -pie seems to be some sort of argument you're using?

I was wondering if this is something you could quickly remove or put in some condition (i.e. use "-pie" only if target minimum sdk is lower then 4.2 etc) ?

I'm on Windows PC, so can't really compile the sourcecode myself, (not that I have know how :) but I'd appreciate if you find a bit of time to have a look at this issue..

Many Thanks

Slavomir

**Comment by profelis** [comment]
have same problem (some info here http://forums.adobe.com/message/5345743 )

**Comment by alebianco** [comment]
the new release should support air 3.8 without issues

**Comment by SlavomirDurej** [comment]
thank you alebianco.
My app made with AIR 3.7 is already in store now, but perhaps on the next one I'll be able to use 3.8 :)

**Comment by fu-iq12** [comment]
Hi, thanks for the update!
could you commit the updated ANE in the development branch?

**Comment by alebianco** [comment]
nope, the dev branch is now under active development to support the final version (v3) of the Google Analytics SDK
the previous version has been merged into the master branch, you should be able to use that release with air 3.8

**Comment by SlavomirDurej** [comment]
cheers Alessandro!.. 

btw, have you tried it with Air 3.9 as well ? We have to use 3.9 shortly as 3.8 doesn't support the new iOS7 icon sizes..

**Comment by alebianco** [comment]
i'm not expecting any changes on the native extensions front from AIR 3.9, so you should be able to use it straight away ... but since you never know with these things and given that i take my sweet time to make an update, i'd suggest you to try it asap with the beta version and eventually raise an issue so i can plan it in my pipeline

**Comment by fu-iq12** [comment]
Since the latest ANE is 3 month old and the AIR3.8 update was 10 days ago I assumed that ANE wouldn't work but it does.

Thank you again! Great extension!

**Comment by SlavomirDurej** [comment]
just tested v2.0.4_201307011119 with AIR 3.9 Beta. Unfortunately tracking wasn't showing up.. Does it still works with GA web profiles ? Or it needs to be a mobile type now ?

**Comment by alebianco** [comment]
exclusively app profiles, the use of web profiles is discouraged in the new versions of the analytics sdk (2.x and 3.x) 
if you need to keep using a web profile you'll to use an older tag (1.xx)

**Comment by SlavomirDurej** [comment]
re :"if you need to keep using a web profile you'll to use an older tag (1.xx)" 

Where do I set this tag ?

**Comment by alebianco** [comment]
https://github.com/alebianco/ANE-Google-Analytics/releases
