### ISSUE TITLE
Some events are not getting tracked

### ISSUE THREAD

**Issue by zarnaagames** [alebianco/ANE-Google-Analytics#23]
Hi,
I tried an example that you provided.
## Here is my code-

// Track an event
tracker.buildEvent("click", "button").withLabel("play").withValue(10).track();
tracker.buildEvent("click", "button").withLabel("stop").track();
tracker.buildEvent("swipe", "screen").withValue(1).track();
tracker.buildEvent("app", "quit").track();
##  tracker.buildSocial("Facebook", "like").track();

Now I can see events on google but only 1st 2 events are appearing on dashboard.
I observed that only events with label are getting tracked.
 tracker.buildSocial events are not getting tracked at all.

What to do???
Am I doing something wrong????

Please let me know

**Comment by alebianco** [comment]
I'll have a look in the next couple of days and I'll let you know. 
on which platform and with which version did you noticed the issue? 
have you noticed any error reported in the device's console?

**Comment by sattaman** [comment]
I have also noticed social events not being tracked, have used normal events instead

**Comment by Eternalspirit** [comment]
I don't think an app is allowed to do +1 Google, like on facebook, etc. on behalf of a user, so it's probably impossible to track social events from an app (unless you can actually find a way to integrate those buttons directly into your app that then send a request to Google/Facebook, it's probably possible with Facebook graph API but I dunno about Google).

**Comment by alebianco** [comment]
@sattaman & @zarnaagames a fix is coming, don't despair
@Eternalspirit the extension is not meant to do have any kind of interaction with social networks. after your app makes that kind of action, using other extensions, you can track it on analytics. that's it

**Comment by Eternalspirit** [comment]
@alebianco That makes sense. :)

**Comment by alebianco** [comment]
I verified and fixed the bug on Android but I still need to check it on iOS.
Have you experienced the same problem on both platforms?
