### ISSUE TITLE
Error on deploy to iOS7

### ISSUE THREAD

**Issue by jBachalo** [alebianco/ANE-Google-Analytics#29]
Getting a strange error on deploy-publish

Invalid input.

Id: -pie can only be used when targeting iOS 4.2 or later

Im compiling with the latest AIR(3.9) SDK using the FlashCS6 IDE.

**Comment by tommyarnott** [comment]
We are also getting the same issue. This post sums things up well: http://forums.adobe.com/message/5325016

Are there any plans to look into a fix? Or is there a known workaround using Flash CS6?

Thanks in advance.

**Comment by alebianco** [comment]
thanks @tommyarnott for the article
they're suggesting to increase ios_version_min value to 4.3, but my extension has been using that value for almost a year.
the latest build on master should already have been done with AIR 3.9 but I'll rebuild it just in case.
in case the problem persist, could someone provide a simple project to show the issue?

**Comment by tommyarnott** [comment]
Thanks for getting back @alebianco. If you could rebuild that would be great. If it doesn't work I'll try to get you over a simple CS6 project as an example with the error being kicked out.

**Comment by alebianco** [comment]
just pushed the update, see if it works

in other news, that was my 200th commit on the project, it needs some kind of celebration.

**Comment by alebianco** [comment]
since I dind't get any update or complaints, I'll assume it's all fixed and working as expected now

**Comment by tommyarnott** [comment]
Hi @alebianco,

Sorry my apologies for the lack of response -Yes the updated build worked fine for us. Thanks again for the fix.
