### ISSUE TITLE
deleteCustomVar

### ISSUE THREAD

**Issue by digitaljohn** [alebianco/ANE-Google-Analytics#3]
There does not seem to be an equivalent of deleteCustomVar?

https://developers.google.com/analytics/devguides/collection/gajs/methods/gaJSApiBasicConfiguration#_gat.GA_Tracker_._deleteCustomVar

**Comment by alebianco** [comment]
There's no equivalent to _deleteCustomVar in the mobile SDKs
https://developers.google.com/analytics/devguides/collection/android/devguide

Apparently all that method does (on the web version) is remove the variable name from the ga cookie, it doesn't remove past data.
The mobile SDKs doesn't use a cookie, so I guess there was no need to implement the method from their part.
