### ISSUE TITLE
ASDoc Error while re-compiling ActionScript

### ISSUE THREAD

**Issue by sumeetbasak** [alebianco/ANE-Google-Analytics#30]
I am getting the following error while re-compiling the swc using the standard build and script.
the process works fine until, it starts generating the asdoc.

Heres a snipet  of the last output.
...
     [echo] [test] Finished running Unit Tests

asdoc:
     [echo] [asdoc] Generating ASDOC documentation
     [java] Adobe ASDoc 
     [java] Version 4.6.0 build 23201
     [java] Copyright (c) 2004-2011 Adobe Systems, Inc. All rights reserved.
     [java] 
     [java] Error: no default arguments are expected
     [java] 
     [java] Use 'asdoc -help' for information about using the command line.

BUILD FAILED
/Users/sumeet/codebase/GIT/ANE-Google-Analytics/source/actionscript/abcore/build/build.xml:72: Java returned: 1

The whole node starting from line 70from the build.xml is as follows:
    <target name="asdoc" depends="test" description="Build Documentation">
       <echo>[asdoc] Generating ASDOC documentation</echo>
        <java jar="${FLEX_HOME}/lib/asdoc.jar" dir="${FLEX_HOME}/frameworks" fork="true" failonerror="true">
            <arg line="-external-library-path+=${lib.dir}"/>
            <arg line="-doc-sources+=${main.src.dir}"/>
            <arg line="-source-path+=${main.src.dir}"/>
            <arg line="-library-path+=libs\air"/>
            <arg line="-output ${doc.dir}"/>
            <arg value="-keep-xml=true"/>
            <arg value="-lenient=true"/>
            <arg line="-window-title 'ABCore ${version.num}'"/>
            <arg line="-main-title 'ABCore ${version.num}'"/>
            <arg line="-footer 'ABCore - https://github.com/alebianco/abcore'"/>
        </java>
        <echo>[asdoc] ASDOC documentation generated successfully</echo>
    </target>

I am trying my hand at updating the GAService JAR to v3 and implement the Campaign and Reffereral tracking.

i have forked your code created a brach from the development stub.
Let me know if you will need more information.

**Comment by alebianco** [comment]
you're using a recent SDK from the Apache Flex project right?
I've noticed the same issue in another project of mine but haven't investigated/fixed it yet. 

did you managed to fixed it? otherwise I'd suggest to disable the asdoc generation for now and just compile the code ...
I'm reviewing all the build process anyway, trying to move away from ANT so I'll have a look at the problem before the next major release.

**Comment by sumeetbasak** [comment]
thanks. I could not fix it but disabled the asdoc generator and moved
forward.

Well i have digressed from that problem to something else now - i want to
get this campaign tracking business solved by hook or by crook.

I am looking at solutions that can wrap an existing apks with some more
binaries ( like ad networks do to put pre-roll ads- like this network does
http://www.vserv.mobi/appwrapper/ )

Most of my projects are running in flash but some are running using
phonegap / marmalade. so i will need a solution to get going for all.

i have made some changes to your codebase to add getCampaignParameters
function to extract the params and pass it to flash. unfortunately, i will
need more time to complete test and complete that.

Will keep you posted on that.

On Wed, Feb 5, 2014 at 2:18 PM, Alessandro Bianco
notifications@github.comwrote:

> you're using a recent SDK from the Apache Flex project right?
> I've noticed the same issue in another project of mine but haven't
> investigated/fixed it yet.
> 
> did you managed to fixed it? otherwise I'd suggest to disable the asdoc
> generation for now and just compile the code ...
> I'm reviewing all the build process anyway, trying to move away from ANT
> so I'll have a look at the problem before the next major release.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/alebianco/ANE-Google-Analytics/issues/30#issuecomment-34147287
> .

## 

Thanks
SB.

**Comment by alebianco** [comment]
there's a new branch on the repo, campaign_tracking, where I'm implementing the same feature now. I already have a first implementation done and there's a company testing it on one of their games so I should have a pretty good feedback on what works and what doesn't.
It would be neat to see how you implemented it and then eventually take the best of both solutions into the master branch.

**Comment by sumeetbasak** [comment]
i need to check test my solution, i was busy firefighting projects and could not spend a lot of time.
will do that now.

**Comment by sumeetbasak** [comment]
My solution failed, how ever while testing your campaign tracking i was wondering how would you set the INSTSLL_REFERRER boradcast tag to AndroidManifiest.xml? do u have an example of how to use it?

**Comment by alebianco** [comment]
take the release from the feature branch https://github.com/alebianco/ANE-Google-Analytics/tree/campaign_tracking
and check the implementation in the demo project https://github.com/alebianco/ANE-Google-Analytics-Demo/tree/tracking_campaign

(i just realized the branch names are different, damn it!)

**Comment by alebianco** [comment]
i'll close the issue since it's completely off topic now. raise another one with the proper subject if you need more info
