### ISSUE TITLE
Error creating database

### ISSUE THREAD

**Issue by innocuo** [alebianco/ANE-Google-Analytics#31]
Hey,

this is such a great extension, but I can't make it work, looking in the log, it is complaining that it can't create the google-analytics database:

GAIDataStore openPersistentStoreWithError:] (GAIDataStore.m:89) ERROR: Error opening database with path /Users/user/Library/Application Support/iPhone Simulator/7.0.3/Applications/com.mypp.myapp/Library/googleanalytics-v2.sql: Error Domain=NSCocoaErrorDomain Code=512 "The operation couldn’t be completed. (Cocoa error 512.)" UserInfo=0x7a47c8a0 {reason=Failed to create file; code = 2}

I'm using the ane in flash cc with air 3.9. Do you know what might be the issue? Maybe I'm just missing a setting.

**Comment by innocuo** [comment]
nevermind. It looks like this is a permissions error in the simulator. It works if, after I publish the app to the emulator, I copy a Library folder from another app into the app I have errors with. (in my case the path is /Users/[my user]/Library/Application Support/Iphone Simulator/7.0.3/Applications/com.myapp.myapp/ )

It works fine on the real device. I thought it didn't because google analytics wasn't showing real-time data, but it looks like that was temporary.

Anyway, great work man, this ANE is really useful

**Comment by alebianco** [comment]
I dont' understand how you fixed it ...
In general, I never had any issue with the emulator regarding creating the sql db. Check the demo project https://github.com/alebianco/ANE-Google-Analytics-Demo for more details on how to setup it
