### ISSUE TITLE
Transaction shipping cost set twice

### ISSUE THREAD

**Issue by devon-o** [alebianco/ANE-Google-Analytics#32]
Hello alebianco,

I haven't actually used this ane yet, but it looks quite nice and I thank you for releasing it.

However, while looking over the code to see how it works, I noticed that in TrackData.java trackTransaction() method when a Transaction instance is created with Transaction.Builder, the setShippingCostInMicros() method is called twice. For the tax setting, it should be:
builder.setTotalTaxInMicros((long) (tax \* 1000000));

Easy enough typo, but something to have look at.

Thank you again,

Devon

**Comment by alebianco** [comment]
thanks for pointing that out, I'll fix it as soon as possible
