### ISSUE TITLE
PackageInspectionFailed while building for debug/iOS, AIR 4.0

### ISSUE THREAD

**Issue by par128** [alebianco/ANE-Google-Analytics#33]
Hey, Alessandro!
When I'm trying to debug our app with Flash Builder on iOS device, building fails with "PackageInspectionFailed" error.
I'm using the latest NativeGATracker-v2.0.4.ane built for AIR 4.0.

When I remove NativeGATracker from the app, the debug build is successful and the app is deployed to the device.

Can you help, please?

Thanks for the extension, we are using it in in our YoWindow weather project - http://yowindow.com

Pasha

**Comment by alebianco** [comment]
as i said in the other comment (and i'm reposting here just for tracking's sake):

I haven't changed the build number for the past couple builds (I bknow! it was a mistake!) so: is it a recent build or an old one? can you try with the latest?
I haven't seen that problem since I removed the docs and surely I haven't added them back.

If that doesn't work drop me an email (or post here) with the log of the error and the app descriptor please

**Comment by apimobi** [comment]
HI Alessandro,

First, thanks for your ANE, it's nice job.
I think i have the same issue, here is the message : 
Packaging failed!
Packaging error message: 
Compilation failed while executing : ld64
Packaging output: 
ld: -pie can only be used when targeting iOS 4.2 or later
If you have an idea?

Thanks, Vincent.

**Comment by alebianco** [comment]
Hi Vincent,
can you tell which versions of AIR and of the extension are you using?
And, if it's not, can you try using the latest release?

**Comment by apimobi** [comment]
I use NativeGATracker-v2.0.4.ane
And AIR 4.0.

**Comment by alebianco** [comment]
Upgrade to 2.0.6 then, it's the first release supporting AIR 4.0 officially and your issue should be fixed with it

**Comment by apimobi** [comment]
Ok i thought it was the last release.
I try it, thanks.

**Comment by alebianco** [comment]
I setup the [releases page](https://github.com/alebianco/ANE-Google-Analytics/releases) a few weeks back, to keep better track
You can also subscribe to the [releases RSS feed](https://github.com/alebianco/ANE-Google-Analytics/releases.atom) to get a notification every time a new release comes out

**Comment by apimobi** [comment]
Nice! Thanks.

**Comment by apimobi** [comment]
Hi Alessandro,
in the NativeGATracker-v2.0.6_201402100702.zip it's always the NativeGATracker-v2.0.4.ane.

**Comment by alebianco** [comment]
don't mind the file name, it was a mistake in the build file. have you tried if it works?

**Comment by apimobi** [comment]
Well yes but i have issues and i think it comes from my package...:(
Thanks

**Comment by apimobi** [comment]
Hi Alessandro,

Just to tell you i've made a new test with just your ANE (the version 2.0.6) and it works fine on my iOS and my Android. Thanks.
