### ISSUE TITLE
ANE Live Tracking

### ISSUE THREAD

**Issue by gnomjogson** [alebianco/ANE-Google-Analytics#36]
Hi,

i've setup the Demo in FB4.6 and compiled the application properly on my phone (Android).
After connecting to a test-account, i've send several test "events" and "screen" tracks to this account. It says: "Hit data has been queued for dispatch". I also tried with manual dispatch, but the RealTime tracking in Analytics doenst show any activity.

I also tried your basic setup as discribed on github project page, but also dont get any tracking working.

Did i miss something? Should the "debug" mode display some logging? Don't see any traces there either. Also waited 24h in case livetracking is not supported. Still no events shown in GA.

Best,
Chris

**Comment by alebianco** [comment]
The live data usually take between 1 and 5 minutes to show up on your dashboard and remains available for ~30mins.
Then it becames historycal data and gets archived to be processed in the other dashboards where you'll see it the next day.

This process **DOES** work, I use it all the time.

Just check that:
- you're using a recent release
- you're using a GA app profile (not a web profile)
- after being queued it gets sent to the servers (by default there's a 5 minutes interval before your hits get sent)

The best way to check if the hits are actually sent is to set the **debug** flag on the extension and then watch the console logs for messages sent by the native libraries (they're identified by the GAV2 tag).

**Comment by gnomjogson** [comment]
Thanks for your reply
I don't question that it does works. It just can't get it working here somehow giving no error.
I use the latest release with mobile GA profile.
I tried with basic debug setup you mentioned now:

if (Analytics.isSupported()) {
trace("GA supported...");
var analytics:Analytics = Analytics.getInstance();
analytics.debug = true;
var tracker:ITracker = analytics.getTracker("XXX")
tracker.startNewSession();
tracker.buildView("Home").track();
}

but i don't get any  GAV2 console logs either. 
Hm. I must get something wrong....

**Comment by alebianco** [comment]
the code looks fine, just try to set

```
analytics.dispatchInterval = 5;
```

during debug so the hits will be dispatched every 5 secs instead of 3 mins.

Also, you won't any logs from the native library in your Flash tracer console. You need to use Console (iOS) or the Device Monitor (android) to see the logs of the actual device. There you'll find the traces with the GAV2 tag.

**Comment by gnomjogson** [comment]
Hi,
Thanks for the hint of using the Device Monitor! The traces there pointed me to the error.
It was simple: The app was missed the ACCESS_NETWORK_STATE permission. So GA connect just shutted down silently.

Thanks again for your tips!

**Comment by alebianco** [comment]
Nice!
if you upgrade to the prerelease i just posted today, it now checks the device permissions when you verify if the extension is supported. so instead of failing silently it would say that it's not supported (I guess i should add some kind of warning or notification maybe).

**Comment by gnomjogson** [comment]
Perfect!
