### ISSUE TITLE
Crash on iOS 4.* Devices

### ISSUE THREAD

**Issue by digitaljohn** [alebianco/ANE-Google-Analytics#4]
It appears the usage of [ARC](http://developer.apple.com/library/mac/#releasenotes/ObjectiveC/RN-TransitioningToARC/Introduction/Introduction.html) (Automatic Reference Counting) is an issue on iOS 4.\* flavour devices.

Example Error:

```
<Notice>: dyld: lazy symbol binding failed: Symbol not found: _objc_retain
```

A potential quick fix on this site:
[Using ARC in native extensions](http://blogs.adobe.com/rajorshi/2012/09/06/using-arc-in-native-extensions/)

Any help greatly appreciated!

Regards:

DigitalJohn

**Comment by alebianco** [comment]
fixed the compatibility problem with iOS>4.3

still need to confirm is earlier versions works as expected

**Comment by esp666** [comment]
Hello I had the same problem but with the new ane and swc I get this at compile time

Error occurred while packaging the application:

ld: library not found for -larclite_iphoneos
Compilation failed while executing : ld64

**Comment by alebianco** [comment]
are you on OSX?
do you have the iphone sdk 5.1 installed? which path?

**Comment by esp666** [comment]
Win7, compilling flex project under flash builder 4.6, air 3.4

**Comment by alebianco** [comment]
I fear you really need an osx enviroment to compile the project using the extension. it's a requirement imposed by the way extensions for ios works.

only exception is you're targeting only an android build, in that case we can work out a solution ...

**Comment by esp666** [comment]
It worked with your last version

**Comment by alebianco** [comment]
ok, that's strange :)
i'm going to open a different issue and investigate the problem

**Comment by esp666** [comment]
Ok, thanks. For information I use several ane for ios without any compilation problem.

**Comment by alebianco** [comment]
@esp666 check the other issue i opened and let me know if it's fixed for you. i tested on my machine and it seems to be working again
