### ISSUE TITLE
Improve documentation on usage

### ISSUE THREAD

**Issue by neuronix** [alebianco/ANE-Google-Analytics#40]
Hi,

I've implemented a cross platform solution for GA with the web version & the ANE for mobile. I seem to only be getting web traffic events in the analytics backend.

Where can we view the mobile data? (the only "mobile" data I find is users trying to browse the web version on the mobile device)
Do we need to upgrade the account to "Universal analytics" ?
Is there anything else required for tracking on mobile?

This post feels a bit off topic in regards of your guidelines but can't find information anywhere nor is there another way to bring up such issues.

Thanks,

Cameron

**Comment by alebianco** [comment]
It says on the readme that the extension work with the (relatively) new "Application profile"
Universal analytics should relate only to web/js, it shouldn't affect the native mobile side

**Comment by neuronix** [comment]
I finally found the missing link, I needed to create a mobile profile in the admin section. My naive impression was that GA would have universal reporting with my default profile. Sorry for bothering you.
