### ISSUE TITLE
Runtime error on iOS

### ISSUE THREAD

**Issue by chatmurai** [alebianco/ANE-Google-Analytics#44]
Air 13.0 / iOS 7.1.1
The followig error is raised at runtime with simple code :
<code>
if( Analytics.isSupported() )
{
var analytics:Analytics = Analytics.getInstance();
var tracker:ITracker = analytics.getTracker( 'UA-*******_-_' );
tracker.buildView("Home").track();
}
</code>
ArgumentError: Error #3500: The extension context does not have a method with the name getCampaignData.

**Comment by alebianco** [comment]
That happens only on the 2.0.7 RC 1 but yes, it should not happen.
I already noticed the problem and an update to the release will be published probably this week

**Comment by chatmurai** [comment]
Hi Alessandro, that's a good news since I updated all my projects to AIR 13 last week ;-)
