### ISSUE TITLE
Where is latest release?

### ISSUE THREAD

**Issue by growch** [alebianco/ANE-Google-Analytics#45]
There used to be a "release" folder with the ane and swc but can't find either of those now. Please advise and thanks for the extension.

**Comment by alebianco** [comment]
I moved them to the releases page of github https://github.com/alebianco/ANE-Google-Analytics/releases
Judging by the amount of questions I get about this, I think i should make more evident :D

**Comment by growch** [comment]
Ah, thanks. Was staring right at me, but didn't see it.
