### ISSUE TITLE
TRACK PAGE VIEW  

### ISSUE THREAD

**Issue by sprilucas** [alebianco/ANE-Google-Analytics#48]
Hello! 
First I want to thank you for this library! 

Using your code I wanted to do the following: 
  var tracker: iTracker = analytics.getTracker ("UA-XXXX-3"), 
tracker.buildView ("/ mypage") track ().; 

In a view in google analytics "UA-XXX-2"  was created.  (with the name "miPage")

As I do so it does not create a new view .... I want to use an already created --> "miPage in UA-XXXX-3 " 

 
I want to function as they did to gaForFlash ( How do I do?  ) : 

https://developers.google.com/analytics/devguides/collection/other/flashTrackingSetupFlash?hl=es 

com.google.analytics.AnalyticsTracker import; 
com.google.analytics.GATracker import; 
var tracker: GATracker AnalyticsTracker = new (this, "UA-111-222", "AS3", true); 
playGame.addEventListener (MouseEvent.CLICK, onButtonClick); 
onButtonClick function (event: Event): void 
{
    THIS ----> tracker.trackPageview ("/ myGame1"); 
} 

Thank you very much for your time!

**Comment by alebianco** [comment]
As far as I know views work fine on every platform.
Please use the latest release available and refer to the usage section for an example on how to do it
https://github.com/alebianco/ANE-Google-Analytics/blob/master/README.md#usage
