### ISSUE TITLE
Packaging problem

### ISSUE THREAD

**Issue by alebianco** [alebianco/ANE-Google-Analytics#5]
Packaging an application on windows with AIR 3.4 using version 1.21 of the extension results in an error:

> Error occurred while packaging the application:
> ld: library not found for -larclite_iphoneos
> Compilation failed while executing : ld64

**Comment by alebianco** [comment]
should be fixed under the (new) development branch.
waiting confirmation from the ~~guinea pigs~~ developers involved before merging into the main branch

**Comment by esp666** [comment]
Compilation ok, thank you

**Comment by profelis** [comment]
1.21 version build was ok. (sdk 3.4)

Now

ld: warning: directory not found for option '-L/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/lib/arc'
           ld: library not found for -larclite_iphoneos
           Compilation failed while executing : ld64

**Comment by alebianco** [comment]
checkout the development branch, it should be fixed there

i'm going to merge soon on the main, i just need to run a couple of tests first

**Comment by profelis** [comment]
ups. thanks!

**Comment by profelis** [comment]
with development branch binaries

ld: library not found for -lgcc_s.1
Compilation failed while executing : ld64

**Comment by alebianco** [comment]
open a new issue please and give me some details on your setup (platform, air version etc)
i'm not using (directly) that library so i'll need to investigate the problem
