### ISSUE TITLE
Where is the .ane?

### ISSUE THREAD

**Issue by jpablogn** [alebianco/ANE-Google-Analytics#62]
Hi,

It seems like there is no .ane file.
Could you provide one?

I would like to test it, without having to compile it by myself (I do not know).

Thank you.
J. Pablo.

**Comment by alebianco** [comment]
https://github.com/alebianco/ANE-Google-Analytics/releases

**Comment by jpablogn** [comment]
Hello,

Many thanks alebianco, I will test it.

May I ask you 2 things:
1. I have found below project, and seems to be the same but without the need of using native extensions: https://developers.google.com/analytics/devguides/collection/other/flashTrackingSetupFlash#useAnalytics
   What is the point of using an .ane for something you can do without it (so that you don't have hardware dependencies)?
2. I think I have read at some point that you are compiling this with Air SDK 13. There is an issu with OpenSSL for versions previous to 14 and Google is complaining about apps compiled with those versions (https://forums.adobe.com/thread/1495664). So, may be it is interesting to compile future versión with Air SDK 15 (I have uploaded an app compiled with this versión and there are not complains any more). 

Thanks again.
J. Pablo.

**Comment by jpablogn** [comment]
Hello,

About point 1:
- I test the "goforflash" library (link below) and it is not working fine (some events works somo others do not):
  https://developers.google.com/analytics/devguides/collection/other/flashTrackingSetupFlash#useAnalytics
- I test you extension (NativeGATracker-v2.0.7rc2.ane) in a Motorola XT-615 (Android 2.3.7) and seem to be working perfectly (cogratulations!). I can see all the events in Google Analytics in real time.

Thanks for such a nice job.
J. Pablo.
