### ISSUE TITLE
Universal / 64 bit support

### ISSUE THREAD

**Issue by mparrett** [alebianco/ANE-Google-Analytics#67]
Would it be possible to update for 64 bit support? I tried but I'm in way over my head. This would allow us to build App Store compatible IPAs with the newest versions of AIR. Thanks!

**Comment by mparrett** [comment]
Just wanted to mention I finally succeeded with this. Includes updating most things to v3 API. Happy to issue a pull request.

**Comment by jumzijie** [comment]
hi mparrett, I would like to make a pull request for your updated one!

**Comment by whiteali** [comment]
@mparrett  Thanks for your work :)
Can you provide the .ANE file ? 
Maybe send it to me directly ? 
Thanks !

**Comment by mparrett** [comment]
@whiteali - Sure. Added the .ANE to my fork: https://github.com/mparrett/ANE-Google-Analytics/commit/87b2857f4667db5ba588b6cadc701afee5c88f95

Remember, some of the eCommerce tracking was hastily disabled because we had a deadline to meet. :) Happy to continue working on this as time permits though.

**Comment by nitacawo** [comment]
@mparrett  first of all thank you for your work. Tried your ane build with  latest air 17 beta. Test code seems to work fine on Ios,  but do you have  any idea why it might return on android
ArgumentError: Error #3500 .

code

```
if (Analytics.isSupported()) 
{
    var analytics:Analytics = Analytics.getInstance();
    var tracker:ITracker = analytics.getTracker("UA-588*****-*");
    trace("analytics initialised");
}
else trace("analytics not supported");
```

**Comment by mparrett** [comment]
@nitacawo Just a guess, but this might have something to do with me compiling with java 1.8. We're working on the first android build of our game so we hadn't caught this yet. I'll recompile with 1.6 and update the ANE.

**Comment by mparrett** [comment]
@nitacawo Just pushed a new ANE. Let me know if that works better for you.

**Comment by nitacawo** [comment]
@mparrett  checked, unfortunately error still occurs.

**Comment by mparrett** [comment]
We're finishing up our Android build in the next weeks, so I'll see if I can dig into this a little deeper. There's a good chance some of my modifications to the actionscript need to be accounted for in the java source.

**Comment by nitacawo** [comment]
@mparrett  thanks for trying. Good luck with your project. Well we can still use old ane for android and 64bit for ios for now.

**Comment by fix89** [comment]
Hi @mparrett! Where can I found your .ANE file? Thanks for your work!
EDIT: Ops, I found it ;)

**Comment by VincentPuget** [comment]
Hi,
Thank for your work @mparrett !

However, i'm trying your ANE version included 64bits support and nothing is sent to Google Analytics.
The "real time" panel in Google Analytics interface stay blocked at 0.
(Tested on iphone 4S on IOS 8.0 and iphone6 on IOS 8.2)

I had re-build this ANE.
On Android, no problems (i have replaced setAppVersion by GA_setAppVersion and getVersion by GA_getVersion in GAContext.java file) , data is sent to GA.

In as3 side, Analytics.isSupported() return true and i only use  tracker.buildView(page).track();

Have you any idea what's wrong?
Thx !
VP

**Comment by mparrett** [comment]
@VincentPuget Thanks for the feedback. We found the real-time panel would stay at 0 unless we sent events. As it was a rushed job, I mainly focused on that functionality. Since page views didn't seem to make a difference in the real-time panel, I may have left something broken there. Next time I'm in the project I'll take a look. Best of luck!

**Comment by mparrett** [comment]
@nitacawo Looks like @VincentPuget highlighted some issues for me to fix with the Android/java - so I'll try and get that in next time I'm working on the project. (Hopefully in the next day or so)

**Comment by VincentPuget** [comment]
@mparrett Effectively, your ANE works fine with events (real-time panel is updated). Thx !

**Comment by VincentPuget** [comment]
@mparrett I have find a way to use tracker.buildView(page).track();
In Tacker.m (ios side), in this method : FREObject trackView(FREContext context, id tracker, FREObject *data) (line 406 ~) : 
add [tracker set:kGAIScreenName value:screen]; just before [tracker send:[[GAIDictionaryBuilder createAppView] build]];

**Comment by vicker** [comment]
@mparrett It is great to see an update of the ANE with 64bit. Thumbs up.

However, I am not able to compile the AIR app and push it over to iOS. It keeps returning the following error, which sounds like it is not 64bit compatible.

Error: libNativeGATracker.a are required to have universal iOS libraries. Please contact the ANE developer(s) to get the same.

I am using NativeGATracker-v2.0.7rc2.ane from the downloaded zip file from your repository. Also tried to build the ANE myself but also no luck.

Just FYI, I am using Apache Flex 4.14.1 with AIR 17.0.

**Comment by mparrett** [comment]
@vicker Check out the `update-to-v3-and-64bit` [branch](https://github.com/mparrett/ANE-Google-Analytics/tree/update-to-v3-and-64bit/bin). There's an ANE in the bin folder that should work for you. Also, if you try building it, make sure you're using java 1.6.

**Comment by vicker** [comment]
@mparrett Tried but not working as well. I am using IntelliJ Idea to build the app and it seems the ADT command is incorrect, maybe that is the root cause... still trying.

**Comment by mparrett** [comment]
@vicker I haven't tested packaging this for simulators btw. We're always using `-target ipa-app-store`. Possible when I built the 64bit version, support for those wasn't included. (From what I understand you have to specify some other architectures in the build settings)

**Comment by vicker** [comment]
@mparrett It works perfectly now. Previously stuck with the ADT config and that's nothing related to the ANE itself. Thanks mparrett.

**Comment by hrisunko** [comment]
@mparrett Thanks for the 64bit version on the ANE. It appears though it's only working for tracking events and not views. Is there any known workaround for this without recompiling?

**Comment by ukmunnithan** [comment]
@mparrett The tracking for View is not working for the 64 bit version in iOS build.I tried with tracker.buildView("HomeView").track(); But no updates are shown in the Realtime page :(
I also tried with the events too..That also not shown in the Google Analytics page

@hrisunko Did you get any solution for fixing this issue??

**Comment by pablolemosassis** [comment]
@vicker ,
Could you share your solution with Intellij?
I am facing the exact same problem.
Tks in advance.

**Comment by vicker** [comment]
@pablocabana
Sorry for the late reply. Umm... let me try my very best to call back my memories...
At that time when I hit that error, I have 2 versions of ANE Google Analytics in my project ANE folder. Although I only added one of the ANE into the project's configuration, IntelliJ tries to load the other outdated ANE as well. (Please note that the ADT can only include a folder, not a file) The resolution is to ensure your ANE folder only contains the ANEs that you need.

**Comment by caostar** [comment]
@vicker 
Tks a lot. I believe that was exactly the issue!

**Comment by vicker** [comment]
@caostar
Always welcome :)

**Comment by vicker** [comment]
@mparrett Seems like the ANE no longer work on iOS 9 with Adobe AIR 20. I am not sure whether this is related to the App Transport Security. Any clue?

**Comment by zeh** [comment]
Anyone of any version of this library that actually works using Air 26+ now that iOS 11 is about to be released and make 64 bits required? I haven't had much luck with any of the forks (running into a lot of "Undefined symbols for architecture arm64" errors).

**Comment by mparrett** [comment]
I think we safely can close this issue since it's been over 2 years since any activity. Feel free to re-open if necessary.
