### ISSUE TITLE
Google Analytics v2?

### ISSUE THREAD

**Issue by Seidi** [alebianco/ANE-Google-Analytics#7]
Why you do not use Google Analytics v2?

**Comment by alebianco** [comment]
well, for starters, it wasn't available at the time and i didn't knew about the new release :)

moreover, the v2 it's still on beta. i'm not sure it'll be totally safe to use a beta version on a production product.

that said, i'll start a new branch in the next days to port the library to the new analytics version. You're welcome to keep an eye on it and test it when it's ready

there're also a couple updates in the pipe for the legacy version. i'm just waiting to have a working environment again to test and then push them

**Comment by alebianco** [comment]
done and release in the development branc
