### ISSUE TITLE
Coudnt make it work

### ISSUE THREAD

**Issue by selimanac** [alebianco/ANE-Google-Analytics#8]
Is there a something wrong?  did i missing something? 
http://pastebin.com/bUmFQRcD

Regards

**Comment by alebianco** [comment]
at a first glance the code seems correct

what's the problem? you get some runtime error? nothing is tracked? something else?

also: are you testing on the actual device? which platform?

**Comment by selimanac** [comment]
Looks like everything is working but Google Analytics coudnt retrieve any data. Nothing is tracked yet. I try it on iOS with 2 different devices There isnt any error or any sandbox issue. I try it for a week(almost everyday) and  G analytic status is still Unknown and there isnt any data.

**Comment by alebianco** [comment]
Double check that you're not running in dry mode (from the code is doesn't seems like that, but double check just to be sure)

Also, set it to debug mode, so you could see the dispatch operations on the device logs. In that way you can control if data is actually sent to the analytics servers.

**Comment by i-soy** [comment]
Hi, I have the same issue. I also don't see any debug messages from GA when debug is set to true.

Note:
- I have removed all Android stuff before building the ANE
- also removed the signing part of the ADT process
- we traced the internet calls of the iOS simulator and there is nothing going to Google
- also the google analytics sqlite database is only filling the session start and not the events/pageviews (those should be emptied after sending)

This is the code snippet I use and tried on iOS simulator and the iPad itself:

```
        if(GATracker.isSupported()) 
        {
            trace("tracker is SUPPORTED!!!!");

            // get version number
            var xml : XML = NativeApplication.nativeApplication.applicationDescriptor;
            var ns : Namespace = xml.namespace();
            var version : String = xml.ns::versionNumber;

            // start google analytics
            var tracker:GATracker = GATracker.getInstance();
            tracker.startNewSession(GAConstants.SESSION_KEY);
            tracker.setCustomVar(VariableSlot.FIRST, Capabilities.os, version);

            tracker.trackPageView("deze_pagina");
            tracker.trackEvent("deze_pagina", "deze_action");
        }
        else
        {
            trace("tracker is NOT SUPPORTED!!!!!");
        }
```

It tells me that it is supported.

Hope you can help.

**Comment by alebianco** [comment]
the only thing i'm not sure about is if the simulator actually can send data through the tracker, i'll check it and let you know. tracking from on an actual should work as expected ...

about the debug messages: you're checking the device logs (with logcat for android for example) or the flash/air trace console?

hopefully i'll update the extension with the latest version of the google tracker during this weekend, so i will surely run more tests about data calls ...

**Comment by i-soy** [comment]
Thanks for you quick reply!

On iOS the simulator usually can send to Google Analytics (when working with the native code).

I have checked the device log with Flash Builder console. Tomorrow I'll check the actual log on the Xcode console. Good tip, thanks.

For what version are you updating the code? for 1.5 or for 2.0?

**Comment by alebianco** [comment]
on the FB console you won't see much stuff, mostly error-reports if something goes wrong. the bulk of the operations are done by the native tracker itself, that logs to the device console of course :)

for the update i guess i'll do a mini-update from 1.5 to 1.51 and then i'll switch to a new branch for the 2.0 update, because we'll loose support on older iOS devices (3gs and 3gs if i remember correctly). hope to have both the updates done and tested before monday

**Comment by i-soy** [comment]
I'll check that console then.

Updates sounds good! I think it is only missing the 3g support, cause that it a ARMv6 architecture right? I thought the 3gs is already ARMv7.

**Comment by alebianco** [comment]
yes you're right, we'll lose support only on the 3g

**Comment by i-soy** [comment]
Btw, do I have to sign the ANE with a .p12? Does it matter? Will Apple not reject the app when it is signed?

**Comment by imatrofailo** [comment]
Hi alebianco. Do you think new ANE with support of GA_SDK_2.0 at least for Android platform will be ready by Monday? I've just researched your great library. And are looking to integrate it into my application. Thx.

**Comment by alebianco** [comment]
can't make promises, but that's the intention :)

**Comment by i-soy** [comment]
I'm opening the console in the Xcode organizer. It is telling me only this at the start:

Dec  1 02:06:01 unknown Game[1648] <Warning>: Entering GAExtensionInitializer
Dec  1 02:06:01 unknown Game[1648] <Warning>: Exiting GAExtensionInitializer
Dec  1 02:06:01 unknown Game[1648] <Warning>: Entering GAContextInitializer
Dec  1 02:06:01 unknown Game[1648] <Warning>: Exiting GAContextInitializer

> Dec  1 02:06:02 unknown profiled[1631] <Notice>: (Note ) profiled: Idled.
> Dec  1 02:06:02 unknown profiled[1631] <Notice>: (Note ) profiled: Service stopping.

Is that console the right one?

**Comment by i-soy** [comment]
Do I need to use the slashes in the pageviews etc? Like, /game/category/viewx ?

**Comment by alebianco** [comment]
only if you like it, the tracker (both my bridge and the native library) doesn't force you to

about the console logs: yes, it is correct for when the extension is initialized. after you make some action you should see something like : 
12/1/12 2:01:53.161 PM ANE-GATrackerDemo[2970]: dispatch called
12/1/12 2:01:53.162 PM ANE-GATrackerDemo[2970]: dispatching 1 hits
12/1/12 2:01:53.162 PM ANE-GATrackerDemo[2970]: GET /__utm.gif?utmwv=4.9mi&utmn=1258374361&utmcs=UTF-8&utmsr=320x480&utmsc=24-bit&utmul=en-us&utmp=%2Fios%2Ftry&utmac=<YOUR_ID>&utmcc=__utma%3D1.2033675275.1354366901.1354366901.1354366901.1%3B&utmht=1354366901708&utmqt=11453 HTTP/1.1
Host: www.google-analytics.com
User-Agent: GoogleAnalytics/1.5 (iPhone Simulator; U; CPU iPhone OS 5.1 like Mac OS X; en-us)

btw, i'm testing the extension right now. still waiting for the data to show up on the dashboard, but it seems to be working so far.
One thing you can check is if your instance is getting garbage-collected because defined locally ... you can refer to the demo project bundled with the sources for more details

**Comment by i-soy** [comment]
Okay, thanks. 

I just tried the .ane which is in the bin folder when you download the project. This one seems to work. I.e. It is generating the debug messages. Don't know yet if they will also be in the dashboard.

Can I use that .ane for the release build to apple? Or is it only for local?

Thanks for your quick replies man!

**Comment by alebianco** [comment]
of course you can use it, it's the fully packaged extension and it will work on ios android for both production and development.
no need to fiddle with the code unless you absolutely have to :)

i'm still waiting for todays's tests to show up on my dashboard, hopefully the will during the night so i can move on tomorrow to v2

**Comment by i-soy** [comment]
oh okay, sorry man, I thought it was only for development. I'll use that one then, I think the stats will be available lateron. Thanks again for your fast replies and the good work!

**Comment by i-soy** [comment]
FYI:
Just checked the data which is send on the iOS simulator when calling the ANE methods. I can't find any specify Google Analytics calls. Might be due to the simulator?!

**Comment by i-soy** [comment]
Okay, I see some information in the "HTML" Google Analytics. Not yet in the special "app" Google Analytics. For you information, I have created two different UA codes with both options (HTML and app) http://grab.by/hWKc. The web one is filled now, the app one not yet.

Can it maybe be that the "app" one needs another approach? I'll wait some time extra and let you know if the "app" one  is also filled.

**Comment by alebianco** [comment]
I just verified that the data is tracked as expected ...

In details:
- yesterday i used, for mistake, an invalid account ID so, even if I was seeing the data being sent nothing was recorded on my dashboard of course. Today i noticed the error, changed to a valid and functional ID and the data showed up **within minutes** on the dashboard. Just to be safe in the future I added a validation for the ID provided, so if it doesn't follow the expected format a runtime error is thrown when starting the session.
- I test both page tracking and event tracking on the iOS simulator and on an actual Android device. All the data is being sent and recorded correctly. So we can say the ios simulator works just as a regular device.
- on the Android device there was AdFree installed, who was blocking the tracking to the GA servers, i had to disable it before being able to send data.
- the account i'm using to track the data is a bit "old" so it wasn't created with the special "app" profile which is relatively new. It's just setup as "not a web site". As far as i know this shouldn't be a problem for the tracker, only the data rapresentation on the dashboard will be a bit different. I will try with a new account today, but i don't expect any differences.

In the end, the best help i can provide is:
- check the demo project for an example of implementation
- verify twice (or more) that the account id is correct
- don't run in dry mode if you want the data to be registered!
- if you're running in manual-dispatch mode, remember to call **dispatch()**
- set the tracker in debug mode and check the system logs to see if and when data is sent
- AdFree and similar software may block your data, get rid of 'em

**Comment by i-soy** [comment]
Thanks for you explanation. I'll use the "web" variant for now, this one is working perfect. (within 10 minutes)

**Comment by imatrofailo** [comment]
I've used recent version of ANE_v.1.23 according to your suggestions. I'm not able to see tracking results on GA Dashboard. I've created tracking id for tracking mobile application. And I see following message near my tracking ID on GA admin page - "This is the tracking ID for this Google Analytics property. Use this ID in conjunction with the SDK to send tracking information from your app."
So the question is - can I use ANE_v.1.23 (with integrated GA SDK v.1.5), or do I need to wait for new ANE with integrated GA SDK v.2.0?

**Comment by alebianco** [comment]
I'm still trying to verify it.. 
The docs imply that both versions should work the same but I'm not 100% sure yet. I'll let you know as soon as I know something for certain.
In any case the next version supporting the sdk 2.0 is almost ready to be published..

**Comment by imatrofailo** [comment]
thank you for follow up.

**Comment by alebianco** [comment]
finally figured it out: yes, the new "app" profile accepts data only from the 2.0 (or higher) trackers :-1: 
hold steady while i complete the port of the extension to the new tracker or use the old style profile ...

**Comment by i-soy** [comment]
thanks for figuring out! that explains everything :)

**Comment by imatrofailo** [comment]
thanks for figuring out! Looking forward for ANE with integrated 2.0 SDK.

**Comment by imatrofailo** [comment]
Hi Alebianco, do you have any updates about new ANE with integrated GA 2.0 SDK. Thank you.

**Comment by alebianco** [comment]
some: i made a quick and dirty port of the android version to test it. it's _very_ dirty and it doesn't reflect most of the new functionalities of the new native tracker. 

if you (badly) need it i can push it to the development branch, but it will change a lot before i can say it's ready for the master branch ...

**Comment by imatrofailo** [comment]
thank you for follow up. i will put integration your GA tracking ANE with my application on hold for a short time. It's better to waut for master version... Thank you.

**Comment by imatrofailo** [comment]
Hi Alebianco, do you have any updates about new ANE with integrated GA 2.0 SDK?
Unfortunatly I have new "app" profile and can't use it with 1.5 SDK.

**Comment by alebianco** [comment]
Yep, I have some news indeed!
I made a fresh start yesterday and I already have all the AS3 code and half the Android native code done and tested. 
I should have the extension published before the new year with the demo project following close.
I'm sorry for the delay but, as you can imagine, I've been delayed a bit by work and life :)

**Comment by imatrofailo** [comment]
Good news! Thank you for follow up...i appreciate your outcome.

**Comment by alebianco** [comment]
For anyone still waiting, I just release it!
you'll find it in the development branch since i still need to write some docs and remake the demo project, but the extension itself is complete and is ready.
You can start track your application NAO!
