### ISSUE TITLE
Data is not tracking with new Google tracker (v2.0 beta 4)

### ISSUE THREAD

**Issue by in4ray** [alebianco/ANE-Google-Analytics#9]
I've just created new Google tracker ID for my new applicatio and do see that ANE stopped working for me. Probably because of new GA SDK - Version: 2.0beta4 (January 2013).
Could you please take a look to it and recompile ANE with new GA SDK.

Thx in advance,
-Ihor

**Comment by alebianco** [comment]
tnx for the warning:)
i had a quick look at che changelog, it's possible that's caused by the switch from http to https as the default protocol.
i'll have a look at it tomorrow and let you know ...

**Comment by alebianco** [comment]
I just pushed a new release with the SDK 2.0 beta 4
tested on android 2.3.7 and the iOS simulator, the data is tracked successfully
let me know if it works for you also

**Comment by in4ray** [comment]
Thx for such quick update. Could you please compile ANE binary file. Appreciate your help.

**Comment by in4ray** [comment]
I've just tested new ANE and it works fine. Thx.
